#!/bin/bash
COMMON="--lr 0.0001 --save_folder single --epochs 200 --n_actions 9 --lambda 0.96 --buf 1 --rho 0.1 --rho_epoch 100 --nworker 16 --batch_size 1 --iter_size 4 --backend minecraft --test_iter 50 --nbatches 100 --ldim 256 --n_filters 32,64"
OMP_NUM_THREADS=1 th main.lua --model LSTM --game $1 --test_game $1 $COMMON ${@:2}
