#!/bin/bash
teachers=\
",single/a_visit1_LSTM_r0.1_0.0001.t7"\
",single/a_visit2_LSTM_r0.1_0.0001.t7"\
",single/a_visit3_LSTM_r0.1_0.0001.t7"\
",single/a_visit4_LSTM_r0.1_0.0001.t7"\
", "\
", "\
\
", "\
", "\
",single/a_pickup1_LSTM_r0.1_0.0001.t7"\
",single/a_pickup2_LSTM_r0.1_0.0001.t7"\
",single/a_pickup3_LSTM_r0.1_0.0001.t7"\
",single/a_pickup4_LSTM_r0.1_0.0001.t7"\
\
",single/a_transform1_LSTM_r0.1_0.0001.t7"\
",single/a_transform2_LSTM_r0.1_0.0001.t7"\
", "\
", "\
",single/a_transform3_LSTM_r0.1_0.0001.t7"\
",single/a_transform4_LSTM_r0.1_0.0001.t7"\

OMP_NUM_THREADS=1 th main.lua --game a_subtask_train --test_game a_subtask_val,a_subtask_train,a_subtask_unseen --model FlatPretrain --max_task 1 --lr 0.00025 --save_folder $1 --save $2 --n_filters 16,32,32 --stride 4,1,2 --filter_size 8,1,5 --pad 0,0,0 --pool 0,0,0 --feat_size 6 --nbatches 100 --batch_size 1 --epochs 500 --nworker 16 --test_iter 10 --ch 32 --rho 0.1 --rho_epoch 150 --lambda 0.96 --max_grad_norm 80 ${@:3} --backend "minecraft" --n_actions 9 --teachers "$teachers" --buf 1
